/**
 * Stamps every frame with a hash of its own contents, so replacing a cut is
 * enough to publish it.
 *
 * The clips carry a 30-day `Cache-Control` (see `next.config.ts`), which is
 * right — they are the bulk of the page and a repeat visitor should never
 * re-download them. But a long cache and a stable filename together mean a
 * replaced cut is invisible: the browser holds the old bytes for a month and
 * never asks. That is not hypothetical, it is what happened to the reshot
 * contact, black warrant and holy curse frames — the new files were on the
 * server for hours while every browser that had been to the site kept playing
 * the old ones.
 *
 * The fix is the one the web has used for twenty years: put the content's hash
 * in its name. New bytes mean a new name, a new name means a URL nothing has
 * cached, and the browser fetches it because it has never seen it before. Next
 * does this for everything it bundles into `/_next/static/`; it cannot do it
 * for `public/`, which it serves verbatim. So this does it for `public/`.
 *
 * `media/` is the source and is committed. `public/frames/` is generated and
 * is not — it is rebuilt from scratch on every `dev` and `build`, which is also
 * what stops a stale hash from lingering after a cut is replaced.
 */
import { createHash } from "node:crypto";
import {
  copyFileSync,
  linkSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, extname, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Which source folder becomes which URL folder. The keys are the directory
// names as they were when these lived in `public/`, because that is still how
// the components ask for them — see `src/lib/media.ts`.
const SETS = [
  { from: "desktop-sections", to: "desktop" },
  { from: "mobile-sections", to: "mobile" },
];

const OUT = join(root, "public", "frames");

/**
 * Eight hex characters of SHA-256. Not a security boundary — it only has to
 * distinguish one cut of a frame from the next, and at eight characters two
 * different files colliding is a one-in-four-billion event that would announce
 * itself immediately as the wrong video playing.
 */
function hash(bytes) {
  return createHash("sha256").update(bytes).digest("hex").slice(0, 8);
}

/**
 * A filename safe to put in a URL without escaping it.
 *
 * The source names are human ones — "co founder @ vhs.mp4", "shadows of the
 * moonless nights-D.mp4" — which is right for files a person maintains, and
 * wrong for a URL, where every space becomes `%20`. Nobody reads these
 * generated names, so they may as well be clean.
 */
function slug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Rebuilt from nothing each run: leaving the old output in place would let a
// replaced cut keep its previous hashed file alongside the new one, and the
// stale one would go on being served to anything still holding that URL.
rmSync(OUT, { recursive: true, force: true });

const manifest = {};

for (const { from, to } of SETS) {
  const src = join(root, "media", from);
  const dest = join(OUT, to);
  mkdirSync(dest, { recursive: true });

  for (const file of readdirSync(src).sort()) {
    const ext = extname(file);
    if (!ext) continue;

    const bytes = readFileSync(join(src, file));
    const name = `${slug(basename(file, ext))}.${hash(bytes)}${ext}`;

    // Hard link rather than copy: same bytes, one copy on disk, and these are
    // ~9MB in total that would otherwise be duplicated on every build. Falls
    // back to copying, which is what happens if `media/` and `public/` ever sit
    // on different filesystems.
    try {
      linkSync(join(src, file), join(dest, name));
    } catch {
      copyFileSync(join(src, file), join(dest, name));
    }

    // Keyed by the path the file had when it lived in `public/`, so the
    // components go on naming frames the way a person would.
    manifest[`/${from}/${file}`] = `/frames/${to}/${name}`;
  }
}

const generated = `// GENERATED by scripts/hash-media.mjs — do not edit.
// Regenerated on every \`npm run dev\` and \`npm run build\`.
//
// Maps each frame's readable path to its content-hashed URL. See the script for
// why the hash is there at all.

export const MEDIA: Record<string, string> = ${JSON.stringify(manifest, null, 2)};
`;

writeFileSync(join(root, "src", "lib", "media-manifest.ts"), generated);

console.log(`hash-media: ${Object.keys(manifest).length} files -> public/frames`);
